### ISSUE TITLE
如何安装？

### ISSUE THREAD

**Issue by hrbwaxdoll** [xupp/daban#1]
服务端看了下，不知道如何安装。~~~~~

**Comment by xupp** [comment]
我这个是部属到了leancloud，或者直接下载放到自己的服务器上
![default](https://cloud.githubusercontent.com/assets/13492008/25987268/cee7c7c8-3725-11e7-8054-ee6aa52796e3.png)

**Comment by hrbwaxdoll** [comment]
OK，我试试，谢谢。
